# Extract rb_call_builtin_inits offset from libruby.so
# This symbol is hidden from .dynsym due to -fvisibility=hidden.
# Tries nm → readelf → objdump in order.

set(header "${OUTPUT_FILE}")
set(library "${RUBY_LIBRARY}")

file(WRITE "${header}" "// Auto-generated by URGE build\n")

macro(try_extract tool_cmd pattern)
  execute_process(
    COMMAND sh -c ${tool_cmd}
    OUTPUT_VARIABLE sym_output
    ERROR_QUIET
  )
  string(REGEX MATCH ${pattern} matched "${sym_output}")
  if(matched)
    set(offset "${CMAKE_MATCH_1}")
    set(found TRUE)
  endif()
endmacro()

set(found FALSE)

# Try nm
find_program(NM nm)
if(NM)
  try_extract(
    "\"${NM}\" \"${library}\" 2>/dev/null | grep rb_call_builtin_inits"
    "([0-9a-f]+) . rb_call_builtin_inits"
  )
endif()

# Try readelf if nm didn't find it
if(NOT found)
  find_program(READELF readelf)
  if(READELF)
    try_extract(
      "\"${READELF}\" -s \"${library}\" 2>/dev/null | grep rb_call_builtin_inits"
      "([0-9a-f]+) . rb_call_builtin_inits"
    )
  endif()
endif()

# Try objdump as last resort
if(NOT found)
  find_program(OBJDUMP objdump)
  if(OBJDUMP)
    try_extract(
      "\"${OBJDUMP}\" -t \"${library}\" 2>/dev/null | grep rb_call_builtin_inits"
      "([0-9a-f]+) . rb_call_builtin_inits"
    )
  endif()
endif()

if(found)
  file(APPEND "${header}" "#define MRI_BUILTIN_INITS_OFFSET 0x${offset}\n")
  message(STATUS "rb_call_builtin_inits offset: 0x${offset}")
else()
  message(WARNING "rb_call_builtin_inits not found in ${library} (tried nm/readelf/objdump)")
endif()
